### PR TITLE
Fix compile warning of generated module when use --keep-unknown-field=false

### PR DESCRIPTION
**Pull request by xinz**
related https://github.com/ahamez/protox/issues/28, please review.

### CODE REVIEW

**Review by ahamez — APPROVED** [review]

**Comment by ahamez** [comment]
Thank you! I'll release ASAP a new version with your fix. But before that, I'll add a thing or two to make the generated code more legible.

**Comment by xinz** [comment]
Thanks for your quick reply, please hold on so far, I have one more issue related about `--keep-unknown-fields=false`, please let me comment here for your advise.

1, Here is an empty message definition `bar.proto`:

```
syntax = "proto2";

package Test;

message Bar {}
```

2, When set `--keep-unknown-fields=false` to generate module from `bar.proto`, here is the generated `Test.Bar` module

```elixir
# credo:disable-for-this-file
defmodule(Test.Bar) do
  @moduledoc(false)
  (
    defstruct([])
    (
      @spec(encode(struct) :: {:ok, iodata} | {:error, any})
      def(encode(msg)) do
        try do
          {:ok, encode!(msg)}
        rescue
          e ->
            {:error, e}
        end
      end
      @spec(encode!(struct) :: iodata | no_return)
      def(encode!(msg)) do
        []
      end
      []
      []
      nil
    )
    (
      @spec(decode(binary) :: {:ok, struct} | {:error, any})
      def(decode(bytes)) do
        try do
          {:ok, decode!(bytes)}
        rescue
          e ->
            {:error, e}
        end
      end
      (
        @spec(decode!(binary) :: struct | no_return)
        def(decode!(bytes)) do
          parse_key_value(bytes, struct(Test.Bar))
        end
      )
      (
        @spec(parse_key_value(binary, struct) :: struct)
        defp(parse_key_value(<<>>, msg)) do
          msg
        end
        defp(parse_key_value(bytes, msg)) do
          {field, rest} = case(Protox.Decode.parse_key(bytes)) do
            {0, _, _} ->
              raise(%Protox.IllegalTagError{})
            {tag, wire_type, rest} ->
              {_, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[], rest}
          end
          msg_updated = struct(msg, field)
          parse_key_value(rest, msg_updated)
        end
      )
      []
    )
    @spec(defs() :: %{required(non_neg_integer) => {atom, Protox.Types.kind(), Protox.Types.type()}})
    def(defs()) do
      %{}
    end
    @spec(defs_by_name() :: %{required(atom) => {non_neg_integer, Protox.Types.kind(), Protox.Types.type()}})
    def(defs_by_name()) do
      %{}
    end
    nil
    @spec(required_fields() :: [])
    def(required_fields()) do
      []
    end
    @spec(syntax() :: atom)
    def(syntax()) do
      :proto2
    end
    [@spec(default(atom) :: {:ok, boolean | integer | String.t() | float} | {:error, atom}), [], def(default(_)) do
      {:error, :no_such_field}
    end]
  )
  def(__generated_code__()) do
    "(\n  defstruct([])\n  (\n    @spec(encode(struct) :: {:ok, iodata} | {:error, any})\n    def(encode(msg)) do\n      try do\n        {:ok, encode!(msg)}\n      rescue\n        e ->\n          {:error, e}\n      end\n    end\n    @spec(encode!(struct) :: iodata | no_return)\n    def(encode!(msg)) do\n      []\n    end\n    []\n    []\n    nil\n  )\n  (\n    @spec(decode(binary) :: {:ok, struct} | {:error, any})\n    def(decode(bytes)) do\n      try do\n        {:ok, decode!(bytes)}\n      rescue\n        e ->\n          {:error, e}\n      end\n    end\n    (\n      @spec(decode!(binary) :: struct | no_return)\n      def(decode!(bytes)) do\n        parse_key_value(bytes, struct(Test.Bar))\n      end\n    )\n    (\n      @spec(parse_key_value(binary, struct) :: struct)\n      defp(parse_key_value(<<>>, msg)) do\n        msg\n      end\n      defp(parse_key_value(bytes, msg)) do\n        {field, rest} = case(Protox.Decode.parse_key(bytes)) do\n          {0, _, _} ->\n            raise(%Protox.IllegalTagError{})\n          {tag, wire_type, rest} ->\n            {_, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)\n            {[], rest}\n        end\n        msg_updated = struct(msg, field)\n        parse_key_value(rest, msg_updated)\n      end\n    )\n    []\n  )\n  @spec(defs() :: %{required(non_neg_integer) => {atom, Protox.Types.kind(), Protox.Types.type()}})\n  def(defs()) do\n    %{}\n  end\n  @spec(defs_by_name() :: %{required(atom) => {non_neg_integer, Protox.Types.kind(), Protox.Types.type()}})\n  def(defs_by_name()) do\n    %{}\n  end\n  nil\n  @spec(required_fields() :: [])\n  def(required_fields()) do\n    []\n  end\n  @spec(syntax() :: atom)\n  def(syntax()) do\n    :proto2\n  end\n  [@spec(default(atom) :: {:ok, boolean | integer | String.t() | float} | {:error, atom}), [], def(default(_)) do\n    {:error, :no_such_field}\n  end]\n)"
  end
end

```

3, There is an another compile warning as below:

```
warning: variable "msg" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/elixir_test_bar.ex:17: Test.Bar.encode!/1
```

So far my local adds a `is_map/1` in https://github.com/ahamez/protox/blob/master/lib/protox/define_encoder.ex#L26 to keep the current logic simple for the empty message case, what do you think about this?

Thanks again for your help.

**Comment by ahamez** [comment]
I fixed this in f7664562a1 😉 
This was due to the fact then unknown fields are not kept, a proto message with no fields will have its corresponding `encode!/1 `  function having an empty body. Thus, the `msg` variable would not be used, hence the warning.

**Comment by xinz** [comment]
> I fixed this in [f766456](https://github.com/ahamez/protox/commit/f7664562a1ce1ca913181f85d3d37d37dd386840) 😉
> This was due to the fact then unknown fields are not kept, a proto message with no fields will have its corresponding `encode!/1 `function having an empty body. Thus, the `msg` variable would not be used, hence the warning.

See this now, thanks very much : )

**Comment by xinz** [comment]
Hello,

Excuse me for any interruption, I see this [commit](https://github.com/ahamez/protox/commit/370f26656dd22a5d174ecfed9e53dc14deff7eca) to use `[]` to replace `nil`, I've thought about it to use `[]` before I committed, but this [thread](https://github.com/elixir-lang/elixir/issues/10066) makes me to use `nil`, maybe they have little to do with each other, it is just FYI, both are fine for me.

Thanks.

**Comment by ahamez** [comment]
> Hello,
> 
> Excuse me for any interruption, I see this [commit](https://github.com/ahamez/protox/commit/370f26656dd22a5d174ecfed9e53dc14deff7eca) to use `[]` to replace `nil`, I've thought about it to use `[]` before I committed, but this [thread](https://github.com/elixir-lang/elixir/issues/10066) makes me to use `nil`, maybe they have little to do with each other, it is just FYI, both are fine for me.
> 
> Thanks.

I'm not sure how this commit is related to the choice of `[]` or `nil` in the generated code?  Anyway, it seems fine with the compiler as no warnings are emitted in both cases. In my opinion, it was really only a matter of making the generated code more legible as the `nil` feels a little weird  (certainly it's only a matter of taste 😅). Obviously, if it's really a problem, I'll be happy to revert this!

**Comment by xinz** [comment]
I mean when choose `[]` or `nil`, the `nil` looks like match NOTHING happened, like the `()` case in the `iex` shell, we want to make the generated code more legible is a needed consideration, I agree with you at this point, thanks again.

**Comment by ahamez** [comment]
In any event, the goal is to get rid of these `[]`, but I didn't find a way to do that…
Anyway, thanks to your feedback, I've added tests to make sure that the generated code is correct, so thank you ;-)

**Pull request merged**
